server:
  port: 8080

logging:
  config: classpath:log4j2.xml

task:
  job-group: cdssJobGroup
  trigger-group: cdssTriggerGroup
  job-triggers:
    - name: testJob
      cron-expression: 0/10 * * * * ?
      description: test job
    - name: testJob2
      cron-expression: 0/5 * * * * ?
      description: test job2

spring:
  application:
    name: quartz-demo
  datasource:
    name: quartzDemoDS
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.96.5.19:3306/quartz_demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    cachePrepStmts: true
    prepStmtCacheSize: 300
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
